name: Auto-Run Canaways Quantum Code

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs once per day at midnight UTC
  workflow_dispatch:  # Allows manual execution from GitHub

jobs:
  run-cqc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: qiskit-env
          python-version: 3.9
          auto-activate-base: false

      - name: Check available Qiskit packages
        shell: bash -l {0}
        run: |
          conda init bash
          source ~/.bashrc
          conda search qiskit
          conda search qiskit-aer || echo "Qiskit-Aer not found in Conda"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate qiskit-env
          conda install -c conda-forge qiskit qiskit-aer numpy scipy -y || echo "Installation failed"

      - name: Verify Qiskit installation
        shell: bash -l {0}
        run: |
          conda activate qiskit-env
          python -c "import qiskit; print('Qiskit installed:', qiskit.__version__)"
          python -c "from qiskit import Aer; print('Qiskit-Aer imported successfully')" || echo "Qiskit-Aer import failed"

      - name: Run Canaways Quantum Code
        shell: bash -l {0}
        run: |
          conda activate qiskit-env
          python core_simulations/canaways_quantum_code.py || echo "Code execution failed"

      - name: Auto-commit and push results
        shell: bash -l {0}
        run: |
          conda activate qiskit-env
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Auto-run results update [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
