name: Auto-Run Canaways Quantum Code

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs once per day at midnight UTC
  workflow_dispatch:  # Allows manual execution from GitHub

permissions:
  contents: write  # Ensures GitHub Actions has write access

jobs:
  run-cqc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies (Qiskit-Aer Requirements)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libeigen3-dev libopenblas-dev liblapack-dev \
          ninja-build python3-dev python3-pip python3-setuptools python3-wheel \
          libgomp1 libstdc++6 libtbb2 libtbb-dev
          echo "System dependencies installed."

      - name: Install Qiskit and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qiskit numpy scipy
          if ! python -c "from qiskit import Aer" 2>/dev/null; then
            echo "Qiskit-Aer not found, installing..."
            pip install qiskit-aer --no-cache-dir || echo "Qiskit-Aer installation via pip failed"
          fi

      - name: Debug Python Environment
        run: |
          python -V
          which python
          pip list
          python -c "import sys; print(sys.path)"

      - name: Build & Install Qiskit-Aer from source (if needed)
        run: |
          if ! python -c "from qiskit import Aer" 2>/dev/null; then
            echo "Qiskit-Aer still missing, building from source..."
            git clone --depth=1 https://github.com/Qiskit/qiskit-aer.git || echo "Failed to clone Qiskit-Aer"
            cd qiskit-aer
            python -m pip install . --verbose
            cd ..
          fi
          if ! python -c "from qiskit import Aer" 2>/dev/null; then
            echo "Qiskit-Aer failed to install properly! Checking why..."
            ls -l /opt/hostedtoolcache/Python/3.9.*/x64/lib/python3.9/site-packages/qiskit_aer
            exit 1
          fi

      - name: Reload Python Packages
        run: |
          python -m pip install --upgrade --force-reinstall qiskit-aer
          python -c "import site; print(site.getsitepackages())"

      - name: Verify Qiskit installation
        run: |
          python -c "import qiskit; print('Qiskit installed:', qiskit.__version__)"
          python -c "from qiskit import Aer; print('Qiskit-Aer imported successfully')" || echo "Qiskit-Aer import failed"

      - name: Run Canaways Quantum Code
        run: |
          python core_simulations/canaways_quantum_code.py || echo "Code execution failed"

      - name: Auto-commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Auto-run results update [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main || echo "No changes to push"
